version: '3.5'

services:
  front:
    build:
        context: ./ml-kurkkumopo-frontend
    ports: 
      - 3000:3000

  back: 
    build:
      context: ./ml-kurkkumopo-backend
    ports: 
      - 5000:5000
    volumes: 
      - model:/src/model

  training: 
    build:
      context: ./ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model

volumes:
  model:
  imgs:
