version: '3.5'

services:
    backend:
      build:
        context: ./backend/backend-example-docker/
      environment:
        - FRONT_URL=http://localhost
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=secret
        - DB_HOST=db
      ports:
        - 8000:8000
      command: "npm start"

    frontend:
      build:
        context: ./frontend/frontend-example-docker
      environment:
        - API_URL=http://localhost:8000
      ports: 
        - 5000:5000
      command: "serve -s -l 5000 dist"

    redis:
      image: redis
      ports: 
        - 6379:6379
      command: "redis-server"
      
    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - backend

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=secret
        - PGDATA=/data
      volumes:
        - ./database:/data

volumes:
  database: